# Generated by Django 5.1.3 on 2024-12-10 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable_scheduler_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subjecttable',
            old_name='subject',
            new_name='contact_hours',
        ),
        migrations.RemoveField(
            model_name='departmenttable',
            name='LOGIN_ID',
        ),
        migrations.RemoveField(
            model_name='semestertable',
            name='DEP_ID',
        ),
        migrations.RemoveField(
            model_name='semestertable',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='studenttable',
            name='COLLEGE_ID',
        ),
        migrations.RemoveField(
            model_name='studenttable',
            name='DEP_ID',
        ),
        migrations.AddField(
            model_name='departmenttable',
            name='college_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='timetable_scheduler_app.collegetable'),
        ),
        migrations.AddField(
            model_name='semestertable',
            name='LOGIN_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='timetable_scheduler_app.logintable'),
        ),
        migrations.AddField(
            model_name='semestertable',
            name='semester_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='semestertable',
            name='subjects',
            field=models.ManyToManyField(blank=True, to='timetable_scheduler_app.subjecttable'),
        ),
        migrations.AddField(
            model_name='studenttable',
            name='SEMESTER_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='timetable_scheduler_app.semestertable'),
        ),
        migrations.AddField(
            model_name='subjecttable',
            name='staff_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='timetable_scheduler_app.stafftable'),
        ),
        migrations.AddField(
            model_name='subjecttable',
            name='subject_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stafftable',
            name='COLLEGE_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='timetable_scheduler_app.collegetable'),
        ),
        migrations.AlterField(
            model_name='stafftable',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='timetable_scheduler_app.departmenttable'),
        ),
        migrations.AlterField(
            model_name='stafftable',
            name='lOGIN_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='timetable_scheduler_app.logintable'),
        ),
        migrations.AlterField(
            model_name='studenttable',
            name='LOGIN_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='timetable_scheduler_app.logintable'),
        ),
        migrations.CreateModel(
            name='CourseTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(blank=True, max_length=50, null=True)),
                ('DEP_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='timetable_scheduler_app.departmenttable')),
            ],
        ),
        migrations.AddField(
            model_name='semestertable',
            name='course_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='timetable_scheduler_app.coursetable'),
        ),
        migrations.CreateModel(
            name='TimetableEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=10)),
                ('period', models.IntegerField()),
                ('course_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='timetable_scheduler_app.coursetable')),
                ('staff_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='timetable_scheduler_app.stafftable')),
            ],
        ),
        migrations.DeleteModel(
            name='classTable',
        ),
    ]
