# Generated by Django 5.1.3 on 2024-12-10 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable_scheduler_app', '0002_rename_subject_subjecttable_contact_hours_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collegetable',
            old_name='college_name',
            new_name='college',
        ),
    ]
