# Generated by Django 5.1.3 on 2024-12-16 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable_scheduler_app', '0004_rename_dep_id_coursetable_dep_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semestertable',
            name='subjects',
        ),
        migrations.AddField(
            model_name='semestertable',
            name='subjects',
            field=models.ForeignKey(blank=True, default=12, on_delete=django.db.models.deletion.CASCADE, to='timetable_scheduler_app.subjecttable'),
            preserve_default=False,
        ),
    ]
