# Generated by Django 5.1.3 on 2024-12-18 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable_scheduler_app', '0005_remove_semestertable_subjects_semestertable_subjects'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConflictTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_text', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable_scheduler_app.stafftable')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable_scheduler_app.studenttable')),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_text', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable_scheduler_app.studenttable')),
            ],
        ),
    ]
