# Generated by Django 5.1.3 on 2024-12-19 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable_scheduler_app', '0006_conflicttable_feedbacktable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semestertable',
            name='subjects',
        ),
        migrations.AddField(
            model_name='semestertable',
            name='subjects',
            field=models.ManyToManyField(to='timetable_scheduler_app.subjecttable'),
        ),
    ]
