# Generated by Django 5.1.3 on 2024-12-19 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable_scheduler_app', '0007_remove_semestertable_subjects_semestertable_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbacktable',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable_scheduler_app.logintable'),
        ),
    ]
