# Generated by Django 5.1.3 on 2024-12-22 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable_scheduler_app', '0008_alter_feedbacktable_student_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conflicttable',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='conflicttable',
            name='student_id',
        ),
    ]
