# Generated by Django 5.1.3 on 2024-12-22 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable_scheduler_app', '0009_remove_conflicttable_is_approved_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conflicttable',
            old_name='feedback_text',
            new_name='conflict_text',
        ),
    ]
