# Generated by Django 5.1.3 on 2024-12-22 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable_scheduler_app', '0010_rename_feedback_text_conflicttable_conflict_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stafftable',
            old_name='login_id',
            new_name='login',
        ),
        migrations.RenameField(
            model_name='subjecttable',
            old_name='staff_id',
            new_name='staff',
        ),
    ]
