# Generated by Django 5.1.3 on 2024-12-30 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable_scheduler_app', '0011_rename_login_id_stafftable_login_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timetableentry',
            old_name='staff_id',
            new_name='faculty',
        ),
        migrations.RemoveField(
            model_name='timetableentry',
            name='course_id',
        ),
        migrations.AddField(
            model_name='timetableentry',
            name='cls',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='timetable_scheduler_app.semestertable'),
        ),
        migrations.AddField(
            model_name='timetableentry',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='timetable_scheduler_app.subjecttable'),
        ),
    ]
