# Generated by Django 5.1.3 on 2024-12-30 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable_scheduler_app', '0012_rename_staff_id_timetableentry_faculty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semestertable',
            name='subjects',
            field=models.ManyToManyField(related_name='class1', to='timetable_scheduler_app.subjecttable'),
        ),
    ]
