# Generated by Django 5.1.3 on 2024-12-30 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable_scheduler_app', '0013_alter_semestertable_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjecttable',
            name='contact_hours',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
