# Generated by Django 5.1.3 on 2025-01-05 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable_scheduler_app', '0014_alter_subjecttable_contact_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegetable',
            name='login',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='timetable_scheduler_app.logintable'),
        ),
    ]
