# Generated by Django 5.1.3 on 2025-01-10 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable_scheduler_app', '0015_collegetable_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='semestertable',
            name='is_odd',
            field=models.BooleanField(default=True),
        ),
    ]
