# Generated by Django 5.1.3 on 2025-01-14 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable_scheduler_app', '0016_semestertable_is_odd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semestertable',
            name='is_odd',
        ),
    ]
