# Generated by Django 5.1.3 on 2025-02-16 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable_scheduler_app', '0017_remove_semestertable_is_odd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studenttable',
            name='semester_id',
        ),
        migrations.AddField(
            model_name='studenttable',
            name='course_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='timetable_scheduler_app.coursetable'),
        ),
    ]
