# Generated by Django 5.1.3 on 2025-02-23 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable_scheduler_app', '0019_otp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTP',
        ),
    ]
