# Generated by Django 5.1.3 on 2025-02-23 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable_scheduler_app', '0021_collegestable_logintable_college_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logintable',
            old_name='college_id',
            new_name='college',
        ),
        migrations.RemoveField(
            model_name='collegestable',
            name='login_id',
        ),
        migrations.RemoveField(
            model_name='collegestable',
            name='password',
        ),
        migrations.RemoveField(
            model_name='collegestable',
            name='place',
        ),
    ]
