# Generated by Django 5.1.3 on 2025-02-24 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable_scheduler_app', '0022_rename_college_id_logintable_college_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logintable',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable_scheduler_app.collegestable'),
        ),
    ]
