# Generated by Django 5.1.3 on 2025-02-24 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable_scheduler_app', '0023_alter_logintable_college'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logintable',
            old_name='college',
            new_name='college_id',
        ),
    ]
